spring.application.name=SEAA-APP

# --- CONFIGURAÇÃO PARA RODAR SOMENTE NO COMPUTADOR (H2 DATABASE) ---
# O banco será um arquivo chamado "seaa_local" na sua pasta de usuário do Windows
#spring.datasource.url=jdbc:h2:file:~/seaa_local;AUTO_SERVER=TRUE
# O "./" aponta para a pasta do seu projeto. 
# O "dados/" cria a pasta automaticamente se ela não existir.
spring.datasource.url=jdbc:h2:file:./dados/seaa_local;MODE=MySQL;DATABASE_TO_UPPER=FALSE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;AUTO_SERVER=TRUE
#spring.datasource.url=jdbc:h2:file:~/seaa_local;MODE=MySQL;DATABASE_TO_UPPER=FALSE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=



# H2 Console (Para você acessar o banco pelo navegador em: localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# JPA / Hibernate - Ajustado para o Dialeto do H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configurações de Pool (Mantidas e ajustadas para local)
spring.datasource.hikari.maximumPoolSize=10
spring.datasource.hikari.connectionTimeout=20000