spring.application.name=SEAA-APP

# --- CONFIGURAÇÃO POSTGRESQL (RENDER - AJUSTE DE SSL) ---
# Adicionado sslmode=require para evitar a busca pelo arquivo root.crt no servidor
spring.datasource.url=jdbc:postgresql://dpg-d6md8s5actks7380ergg-a-a.oregon-postgres.render.com:5432/seaa_db_prod?ssl=true&sslmode=require
spring.datasource.username=seaa_db_prod_user
spring.datasource.password=764REcUuoFYKDO4pQv5FAwhs9TzvZqHl
spring.datasource.driverClassName=org.postgresql.Driver

# Dialeto e JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- OTIMIZAÇÃO HIKARI ---
spring.datasource.hikari.keepaliveTime=30000
spring.datasource.hikari.maximumPoolSize=5
spring.datasource.hikari.connectionTimeout=20000